---
title: "Course09-Assignment-Week02"
author: "Henrique I. Neves"
date: "15/03/2021"
output: html_document
runtime: shiny
---
A simple map to show an interactive map and mark as many point as wanted in the area of São Paulo.

Please, input the information required:
```{r, echo = FALSE}
sliderInput("points", "How many points to be marked on the map?", min = 0, max = 1000, value = 0,
            width = 1000)
sliderInput("lat", "Insert range of latitude:", min = -90, max = 90, value = c(-90,90), step = 0.0001, width = 1000)
sliderInput("lng", "Insert range of longitude:", min = -180, max = 180, value = c(-180, 180), step = 0.0001, width = 1000)
radioButtons("mark", "Choose the type of mark:", choices = c("Standard", "Arrow", "Dollar", "Communism"))
```
```{r, echo = FALSE}
library(leaflet)
output$map <- renderLeaflet({
  df <- data.frame(lat = runif(input$points, min = input$lat[1], max = input$lat[2]),
                   lng = runif(input$points, min = input$lng[1], max = input$lng[2]))
  if (input$mark == "Standard"){
    df %>% leaflet() %>% addTiles() %>% addMarkers()
  }else if (input$mark == "Arrow"){
    df %>% leaflet() %>% addTiles() %>% addMarkers(icon = makeIcon(
      iconUrl = "https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-arrow-down-b-512.png",
      iconWidth = 30, iconHeight = 30
    ))
  }else if (input$mark == "Dollar"){
    df %>% leaflet() %>% addTiles() %>% addMarkers(icon = makeIcon(
      iconUrl = "https://image.flaticon.com/icons/png/512/8/8817.png",
      iconWidth = 30, iconHeight = 30
    ))
  }else if (input$mark == "Communism"){
    df %>% leaflet() %>% addTiles() %>% addMarkers(icon = makeIcon(
      iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Hammer_and_sickle_red_on_transparent.svg/1200px-Hammer_and_sickle_red_on_transparent.svg.png",
      iconWidth = 30, iconHeight = 30
    ))    
  }
  
    })
```
```{r, echo=FALSE}
leafletOutput("map")
```





